### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by TheWyter** [trentech/ProjectWorlds#109]
Server is running well over many days and after a restart now this:

> [19:11:38] [Server thread/INFO] [minecraft/DedicatedServer]: Preparing level "world"
> [19:11:38] [Server thread/ERROR] [minecraft/SaveFormatOld]: Exception reading .\world\level.dat
> java.io.EOFException: null
>         at java.util.zip.GZIPInputStream.readUByte(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readUShort(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:26) ~[gi.class:?]
>         at net.minecraft.world.storage.SaveFormatOld.func_186353_a(SaveFormatOld.java:101) [bfc.class:?]
>         at net.minecraft.world.storage.SaveFormatOld.func_75803_c(SaveFormatOld.java:83) [bfc.class:?]
>         at net.minecraft.world.chunk.storage.AnvilSaveConverter.func_75801_b(SourceFile:96) [bez.class:?]
>         at net.minecraft.server.MinecraftServer.func_71237_c(MinecraftServer.java:176) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4393) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
> [19:11:38] [Server thread/INFO] [Sponge]: Checking for worlds that need to be migrated...
> [19:11:38] [Server thread/INFO] [Sponge]: No worlds were found in need of migration.
> [19:11:38] [Server thread/ERROR] [Sponge]: Failed loading Sponge data for World [DIM-1]}. Report to Sponge ASAP.
> java.io.EOFException: null
>         at java.util.zip.GZIPInputStream.readUByte(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readUShort(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:26) ~[gi.class:?]
>         at org.spongepowered.common.world.WorldManager.registerExistingSpongeDimensions(WorldManager.java:982) [WorldManager.class:1.12.2-2838-7.1.7]
>         at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:699) [WorldManager.class:1.12.2-2838-7.1.7]
>         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4397) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
> [19:11:38] [Server thread/ERROR] [Sponge]: Failed loading Sponge data for World [DIM1]}. Report to Sponge ASAP.
> java.io.EOFException: null
>         at java.util.zip.GZIPInputStream.readUByte(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readUShort(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:26) ~[gi.class:?]
>         at org.spongepowered.common.world.WorldManager.registerExistingSpongeDimensions(WorldManager.java:982) [WorldManager.class:1.12.2-2838-7.1.7]
>         at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:699) [WorldManager.class:1.12.2-2838-7.1.7]
>         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4397) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
> [19:11:38] [Server thread/ERROR] [Sponge]: Failed loading Sponge data for World [LosMiddle]}. Report to Sponge ASAP.
> java.io.EOFException: null
>         at java.util.zip.GZIPInputStream.readUByte(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readUShort(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:26) ~[gi.class:?]
>         at org.spongepowered.common.world.WorldManager.registerExistingSpongeDimensions(WorldManager.java:982) [WorldManager.class:1.12.2-2838-7.1.7]
>         at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:699) [WorldManager.class:1.12.2-2838-7.1.7]
>         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4397) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
> [19:11:38] [Server thread/ERROR] [Sponge]: Failed loading Sponge data for World [Space]}. Report to Sponge ASAP.
> java.io.EOFException: null
>         at java.util.zip.GZIPInputStream.readUByte(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readUShort(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:26) ~[gi.class:?]
>         at org.spongepowered.common.world.WorldManager.registerExistingSpongeDimensions(WorldManager.java:982) [WorldManager.class:1.12.2-2838-7.1.7]
>         at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:699) [WorldManager.class:1.12.2-2838-7.1.7]
>         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4397) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
> [19:11:38] [Server thread/ERROR] [minecraft/SaveFormatOld]: Exception reading .\world\level.dat
> java.io.EOFException: null
>         at java.util.zip.GZIPInputStream.readUByte(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readUShort(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:26) ~[gi.class:?]
>         at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:117) [bfc.class:?]
>         at net.minecraft.world.storage.SaveHandler.redirect$forgeImpl$hookToUpdateSpongeLoadData$bap000(SaveHandler.java:1577) [bfb.class:?]
>         at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122) [bfb.class:?]
>         at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:744) [WorldManager.class:1.12.2-2838-7.1.7]
>         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4397) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
> [19:11:38] [Server thread/INFO] [FML]: Injecting existing registry data into this server instance
> [19:11:40] [Server thread/INFO] [FML]: Applying holder lookups
> [19:11:40] [Server thread/INFO] [FML]: Holder lookups applied
> [19:11:40] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
> java.lang.RuntimeException: Exception trying to load level_sponge.dat, file corruption maybe?
>         at net.minecraft.world.storage.SaveHandler.redirect$forgeImpl$hookToUpdateSpongeLoadData$bap000(SaveHandler.java:1582) ~[bfb.class:?]
>         at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:132) ~[bfb.class:?]
>         at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:744) ~[WorldManager.class:1.12.2-2838-7.1.7]
>         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4397) ~[MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) ~[nz.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
> Caused by: java.lang.RuntimeException: Attempt failed when reading Sponge level data for [world] from file [level_sponge.dat]!
>         at net.minecraft.world.storage.SaveHandler.bridge$loadSpongeDatData(SaveHandler.java:1175) ~[bfb.class:?]
>         at net.minecraft.world.storage.SaveHandler.redirect$forgeImpl$hookToUpdateSpongeLoadData$bap000(SaveHandler.java:1580) ~[bfb.class:?]
>         ... 6 more
> Caused by: java.io.EOFException
>         at java.util.zip.GZIPInputStream.readUByte(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readUShort(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_231]
>         at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:26) ~[gi.class:?]
>         at net.minecraft.world.storage.SaveHandler.bridge$loadSpongeDatData(SaveHandler.java:1172) ~[bfb.class:?]
>         at net.minecraft.world.storage.SaveHandler.redirect$forgeImpl$hookToUpdateSpongeLoadData$bap000(SaveHandler.java:1580) ~[bfb.class:?]
>         ... 6 more
> [19:11:40] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: E:\2. Desktop\Server\Spigot Backups\29.01\.\crash-reports\crash-2020-01-29_19.11.40-server.txt
> [19:11:40] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
> [19:11:40] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
> [19:11:40] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
> [19:11:40] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.

Please help. :(

**Comment by TheWyter** [comment]
Here are the report of the crash-reports folder.

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   CamPatchingLoader (CMDCam_v1.4.4_mc1.12.2.jar)
>   CreativePatchingLoader (CreativeCore_v1.9.77_mc1.12.2.jar)
>   BlockbusterCore (blockbuster-1.6.1-1.12.2.jar)
>   CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
>   SpongeCoremod (spongeforge-1.12.2-2838-7.1.7.jar)
>   McLib core mod (mclib-1.0.3-1.12.2.jar)
> Contact their authors BEFORE contacting forge
> 
> // I bet Cylons wouldn't have this problem.
> 
> Time: 29.01.20 19:19
> Description: Exception in server tick loop
> 
> java.lang.RuntimeException: Exception trying to load level_sponge.dat, file corruption maybe?
> 	at net.minecraft.world.storage.SaveHandler.redirect$forgeImpl$hookToUpdateSpongeLoadData$bap000(SaveHandler.java:1582)
> 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122)
> 	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:744)
> 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4397)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.RuntimeException: Attempt failed when reading Sponge level data for [world] from file [level_sponge.dat]!
> 	at net.minecraft.world.storage.SaveHandler.bridge$loadSpongeDatData(SaveHandler.java:1175)
> 	at net.minecraft.world.storage.SaveHandler.redirect$forgeImpl$hookToUpdateSpongeLoadData$bap000(SaveHandler.java:1580)
> 	... 6 more
> Caused by: java.io.EOFException
> 	at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
> 	at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
> 	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
> 	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
> 	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
> 	at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:26)
> 	at net.minecraft.world.storage.SaveHandler.bridge$loadSpongeDatData(SaveHandler.java:1172)
> 	... 7 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at net.minecraft.world.storage.SaveHandler.redirect$forgeImpl$hookToUpdateSpongeLoadData$bap000(SaveHandler.java:1582)
> 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122)
> 
> -- Sponge PhaseTracker --
> Details:
> 	Phase Stack: [Empty stack]
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zje000(MinecraftServer.java:4721)
> 	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
> 	at java.lang.Thread.run(Unknown Source)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_231, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 784210464 bytes (747 MB) / 2529165312 bytes (2412 MB) up to 3817865216 bytes (3641 MB)
> 	JVM Flags: 1 total; -Xmx4096M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.5.2847 26 mods loaded, 24 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	Mods:
> 
> 	| State  | ID                | Version           | Source                              | Signature |
> 	|:------ |:----------------- |:----------------- |:----------------------------------- |:--------- |
> 	| LCHIJA | minecraft         | 1.12.2            | minecraft.jar                       | None      |
> 	| LCHIJA | mcp               | 9.42              | minecraft.jar                       | None      |
> 	| LCHIJA | FML               | 8.0.99.99         | forge.jar                           | None      |
> 	| LCHIJA | forge             | 14.23.5.2847      | forge.jar                           | None      |
> 	| LCHIJA | creativecoredummy | 1.0.0             | minecraft.jar                       | None      |
> 	| LCHIJA | spongeapi         | 7.1.0-0b58730f    | spongeforge-1.12.2-2838-7.1.7.jar   | None      |
> 	| LCHIJA | sponge            | 1.12.2-7.1.7      | spongeforge-1.12.2-2838-7.1.7.jar   | None      |
> 	| LCHIJA | spongeforge       | 1.12.2-2838-7.1.7 | spongeforge-1.12.2-2838-7.1.7.jar   | None      |
> 	| LCHIJA | mclib             | 1.0.3             | mclib-1.0.3-1.12.2.jar              | None      |
> 	| LCHIJA | aperture          | 1.3.2             | aperture-1.3.2-1.12.2.jar           | None      |
> 	| LCHIJA | metamorph         | 1.1.9             | metamorph-1.1.9-1.12.2.jar          | None      |
> 	| LCHIJA | blockbuster       | 1.6.1             | blockbuster-1.6.1-1.12.2.jar        | None      |
> 	| LCHIJA | cfm               | 6.3.0             | cfm-6.3.0-mc1.12.2.jar              | None      |
> 	| LCHIJA | chisel            | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44.jar        | None      |
> 	| LCHIJA | chiselsandbits    | 14.33             | chiselsandbits-14.33.jar            | None      |
> 	| LCHIJA | cmdcam            | 1.4.0             | CMDCam_v1.4.4_mc1.12.2.jar          | None      |
> 	| LCHIJA | creativecore      | 1.9.9             | CreativeCore_v1.9.77_mc1.12.2.jar   | None      |
> 	| LCHIJA | props             | 2.6.3             | Decocraft-2.6.3_1.12.2.jar          | None      |
> 	| LCHIJA | emoticons         | 0.3.2             | emoticons-0.3.2-1.12.2-dist.jar     | None      |
> 	| LCHIJA | modernlamps       | 1.0.3             | ModernLights-1.0.3_1.12.jar         | None      |
> 	| LCHIJA | opframe           | 1.4.0             | Online-Picture-Frame-Mod-1.12.2.jar | None      |
> 	| UD     | blockbuster_core  | 1.6.1             | minecraft.jar                       | None      |
> 	| UD     | mclib_core        | 1.0.3             | minecraft.jar                       | None      |
> 
> 
> 	Plugins:
> 
> 	| State  | ID        | Version         | Source                                             | Signature |
> 	|:------ |:--------- |:--------------- |:-------------------------------------------------- |:--------- |
> 	| LCHIJA | pjc       | 0.3.0           | projectcore-7.2.0-0.3.0.jar                        | None      |
> 	| LCHIJA | pjw       | 0.13.1          | projectworlds-7.2.0-0.13.1.jar                     | None      |
> 	| LCHIJA | worldedit | 6.1.10-SNAPSHOT | worldedit-sponge-api7.1.0-6.1.10-SNAPSHOT-dist.jar | None      |
> 
> 	Loaded coremods (and transformers): 
> CamPatchingLoader (CMDCam_v1.4.4_mc1.12.2.jar)
>   com.creativemd.cmdcam.transform.CamTransformer
> CreativePatchingLoader (CreativeCore_v1.9.77_mc1.12.2.jar)
>   
> BlockbusterCore (blockbuster-1.6.1-1.12.2.jar)
>   mchorse.blockbuster.core.BBCoreClassTransformer
> CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
>   team.chisel.ctm.client.asm.CTMTransformer
> SpongeCoremod (spongeforge-1.12.2-2838-7.1.7.jar)
>   org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
> McLib core mod (mclib-1.0.3-1.12.2.jar)
>   mchorse.mclib.core.McLibCMClassTransformer
> 	Profiler Position: N/A (disabled)
> 	Player Count: 0 / 20; []
> 	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
> 	Type: Dedicated Server (map_server.txt)
