### ISSUE TITLE
World imported that I /world setspawn kicks me from server and now wont let me /world load it

### ISSUE THREAD

**Issue by MrRobotVPN** [trentech/ProjectWorlds#113]
I downloaded a void world and then loaded it up in vanilla 1.12.2 to avoid conflictions
I set the spawn point on a single block in that world. I then **closed out** of the server
when I rebooted it and loaded in it kept kicking me until I deleted my playerdata
once I loaded back into the default world I tried /world tp void
it was not loaded when I attempted /world load void
It gives this error.

[05:03:40] [Server thread/INFO] [nucleus]: ran the command: /world load market
[05:03:41] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task pjw-S-28 owned by Plugin{id=pjw, name=ProjectWorlds,
version=0.13.1, description=Multi world management plugin, url=http://github.com/TrenTech/ProjectWorlds, authors=[TrenTech], source=
.\mods\projectworlds-7.2.0-0.13.1.jar}, but an error occured.
java.lang.IllegalArgumentException: value already present: df7ced94-c9c7-4846-a7b1-45a43866aa3b
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[minecraft_server.1.12.2.jar:?]
        at org.spongepowered.common.world.WorldManager.registerWorldProperties(WorldManager.java:356) ~[WorldManager.class:1.12.2-28
38-7.1.7]
        at org.spongepowered.common.world.WorldManager.loadWorld(WorldManager.java:649) ~[WorldManager.class:1.12.2-2838-7.1.7]
        at org.spongepowered.common.world.WorldManager.loadWorld(WorldManager.java:604) ~[WorldManager.class:1.12.2-2838-7.1.7]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:2441) ~[MinecraftServer.class:?]
        at com.gmail.trentech.pjw.commands.CommandLoad.lambda$process$0(CommandLoad.java:69) ~[CommandLoad.class:?]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-
2838-7.1.7]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-
2838-7.1.7]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:188) ~[SchedulerBase.class:1.12.2-2838-7.1.
7]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.12.2-2838-7.
1.7]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_241]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2838-7.1.7]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2838-7.1.7]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.1
2.2-2838-7.1.7]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:458) [SpongeMod.class:1.12.2-2838-7.1.7]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[05:03:47] [Server thread/INFO] [nucleus]: ran the command: /gmc
[05:03:52] [pool-3-thread-6/INFO] [playershopsrpg]: Saving Shops to DB
[05:04:02] [Server thread/INFO] [minecraft/DedicatedServer]: Useless pokémon will be wiped away in 5m.
[05:04:15] [Server thread/INFO] [nucleus]: ran the command: /world tp market
[05:04:17] [Server thread/INFO] [nucleus]: ran the command: /world load market
[05:04:18] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task pjw-S-38 owned by Plugin{id=pjw, name=ProjectWorlds,
version=0.13.1, description=Multi world management plugin, url=http://github.com/TrenTech/ProjectWorlds, authors=[TrenTech], source=
.\mods\projectworlds-7.2.0-0.13.1.jar}, but an error occured.
java.lang.IllegalArgumentException: value already present: df7ced94-c9c7-4846-a7b1-45a43866aa3b
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[minecraft_server.1.12.2.jar:?]
        at org.spongepowered.common.world.WorldManager.registerWorldProperties(WorldManager.java:356) ~[WorldManager.class:1.12.2-28
38-7.1.7]
        at org.spongepowered.common.world.WorldManager.loadWorld(WorldManager.java:649) ~[WorldManager.class:1.12.2-2838-7.1.7]
        at org.spongepowered.common.world.WorldManager.loadWorld(WorldManager.java:604) ~[WorldManager.class:1.12.2-2838-7.1.7]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:2441) ~[MinecraftServer.class:?]
        at com.gmail.trentech.pjw.commands.CommandLoad.lambda$process$0(CommandLoad.java:69) ~[CommandLoad.class:?]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-
2838-7.1.7]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-
2838-7.1.7]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:188) ~[SchedulerBase.class:1.12.2-2838-7.1.
7]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.12.2-2838-7.
1.7]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_241]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2838-7.1.7]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2838-7.1.7]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.1
2.2-2838-7.1.7]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:458) [SpongeMod.class:1.12.2-2838-7.1.7]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
> sponge plugins
[05:04:44] [Server thread/INFO] [nucleus]: Server ran the command: /sponge plugins
[05:04:44] [Server thread/INFO] [minecraft/DedicatedServer]: Plugins (49): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Amber, Boop, Nuceles, Ho

when I rebooted again it gives me the error "world not loaded" when I type world tp void
when I type /world load void it says "void does not exist"
when I type /world import void overworld overworld
it says "sponge world detected"

**Comment by MrRobotVPN** [comment]
I fixed the problem by trial and error. 
after /world import void overworld overworld
it said "void imported successfully"
I then had to reboot the server! and then type
/world tp void
and it worked fine. I tried multiple times and it only worked if I rebooted first I am guessing this is a bug in the code. Because if I import ANY world more then once it gives this error or if I unzip a world and import it and there is a corrupt playerdata .dat file. If I remove the .dat file in the player data and then try to reimport it. It gives the error

Error occured while executing command: Catalog type is already register for id: void
and if I fo s server restart and they try to reimport it. It works perfectly fine... Hope you can fix this it took me over an hour to figure out why these errors kept occuring

PS: also it's really annoying that worlds are cap sensitive anyway to add an option the config to ignore caps sensitive worlds just in case some players like it since plugins like bedwarsReloadd only will work with lowercase worlds.

**Comment by MrRobotVPN** [comment]
I booted up my server today and it had replaced the void world with an exact duplicate of my main world. This is the second time it has done this. Is this because I originally loaded the world in Nucleus before I installed Project Worlds and then removed the nucleus?

**Comment by MrRobotVPN** [comment]
reimported the world under a diffrent name straight out of the .zip and when I did /world load and then tpped to it /world tp it gave all these errors.

[03:08:37] [Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[MessageToByteEncoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHand
lerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandl
erContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerCont
ext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerCont
ext.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:548) ~[NetworkDispatcher.c
lass:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHand
lerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChan
nelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerCont
ext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHan
dlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHan
dlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]

        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:?
]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [SingleThreadEventExec
utor.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5
.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
        at net.minecraft.network.play.server.SPacketRespawn.func_148840_b(SourceFile:48) ~[jw.class:?]
        at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:51) ~[ha.class:?]
        at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:12) ~[ha.class:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[MessageToByteEncoder.class:?]
        ... 18 more
[03:08:37] [Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[MessageToByteEncoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHand
lerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandl
erContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerCont
ext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerCont
ext.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:548) ~[NetworkDispatcher.c
lass:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHand
lerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChan
nelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerCont
ext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHan
dlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHan
dlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]

        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:?
]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [SingleThreadEventExec
utor.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5
.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
        at net.minecraft.network.play.server.SPacketServerDifficulty.func_148840_b(SourceFile:35) ~[il.class:?]
        at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:51) ~[ha.class:?]
        at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:12) ~[ha.class:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[MessageToByteEncoder.class:?]
        ... 18 more
[03:08:37] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: lost connection: Internal Exception: io.netty.handler.c
odec.EncoderException: java.lang.NullPointerException
