### ISSUE TITLE
Possible bug in SpongeData

### ISSUE THREAD

**Issue by dpisarenko** [trentech/ProjectWorlds#19]
I noticed the following stack trace when launching Minecraft with `projectworlds-4.1.0-0.9.1.jar`:

```
[20:58:31] [Server thread/ERROR] [Sponge/sponge]: Could not pass FMLServerAboutToStartEvent to org.spongepowered.mod.plugin.SpongeModPluginContainer@d4122
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[?:1.8.0_66]
	at com.gmail.trentech.pjw.io.SpongeData.<init>(SpongeData.java:27) ~[SpongeData.class:?]
	at com.gmail.trentech.pjw.io.SpongeData.init(SpongeData.java:78) ~[SpongeData.class:?]
	at com.gmail.trentech.pjw.Main.onAboutToStartServer(Main.java:59) ~[Main.class:?]
	at org.spongepowered.common.event.listener.GameAboutToStartServerEventListener_Main_onAboutToStartServer6.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.1.0-BETA-1366]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:210) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1366]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:251) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1366]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:185) [SpongeMod.class:1.8.9-1890-4.1.0-BETA-1366]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:857) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:122) [bpo.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

Possible fix: Replace the following code in [SpongeData](https://github.com/trentech/ProjectWorlds/blob/master/src/main/java/com/gmail/trentech/pjw/io/SpongeData.java) 

```
String defaultWorld = Main.getGame().getServer().getDefaultWorld().get().getWorldName();
```

by this:

```
final Optional<World> defaultWorldObj = Main.getGame().getServer().getDefaultWorld();
final String defaultWorld;
if (defaultWorldObj.isPresent()) {
  defaultWorld = defaultWorldObj.get().getWorldName();
} else {
defaultWorld = "";
}
```

**Comment by trentech** [comment]
That would cause more problems later. I assume your still using single player?

**Comment by dpisarenko** [comment]
> I assume your still using single player?

Yes.
