### ISSUE TITLE
NoSuchMethodError on `/world teleport world2:100,63,100`

### ISSUE THREAD

**Issue by dpisarenko** [trentech/ProjectWorlds#20]
When I enter the command `/world teleport world2:100,63,100` or `/world teleport world2`, I get the error given below. Can I fix this error by upgrading to a newer version of Sponge and/or Forge?

```
[11:54:17] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'world teleport world2:100,63,100' for source EntityPlayerMP['dp118m'/848, l='2016_06_04_caw', x=218,77, y=63,00, z=221,28]: org.spongepowered.api.entity.living.player.Player.setLocation(Lorg/spongepowered/api/world/Location;)Z
java.lang.NoSuchMethodError: org.spongepowered.api.entity.living.player.Player.setLocation(Lorg/spongepowered/api/world/Location;)Z
	at com.gmail.trentech.pjw.commands.CMDTeleport.execute(CMDTeleport.java:124) ~[CMDTeleport.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:177) ~[ChildCommandElementExecutor.class:1.8.9-1890-4.1.0-BETA-1366]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:331) ~[CommandSpec.class:1.8.9-1890-4.1.0-BETA-1366]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1890-4.1.0-BETA-1366]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:268) [SpongeCommandManager.class:1.8.9-1890-4.1.0-BETA-1366]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815) [lm.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794) [lm.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:115) [PacketUtil.class:1.8.9-1890-4.1.0-BETA-1366]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152) [bpo.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

**Comment by dpisarenko** [comment]
The same command works perfectly well in the previous version (`projectworlds-4.1.0-0.9.0.jar`).

**Comment by trentech** [comment]
It's because your using an outdated version of SpongeForge. This was mentioned a couple times on the forums by the Sponge developers.

https://forums.spongepowered.org/t/psa-latest-teleportation-api-changes/13019
