### ISSUE TITLE
[1.10.2] World list

### ISSUE THREAD

**Issue by mister-man** [trentech/ProjectWorlds#34]
Hallo together,

if I use the command "/world list", loaded world will shown as unloaded. 

Plugins installed:
- PEX
- PJW
- PJP
- RedProtect

Thanks

**Comment by trentech** [comment]
This is a Sponge bug

**Comment by ThornsOfire** [comment]
Have the same error on "/world list".

Causes the following error to spam console.

SpongeForge: 1.10.2-2079-5.0.0-BETA-1737
PEX: 2.0-SNAPSHOT-b142
PJW: 5.0.0-0.10.4


`[01:17:08] [Server thread/ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.world.MinecraftException: The save folder for world .\world\AMP is being accessed from another location, aborting
        at net.minecraft.world.storage.SaveHandler.func_75762_c(SaveHandler.java:96) ~[azy.class:?]
        at net.minecraft.world.World.func_72906_B(World.java:3430) ~[aid.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:167) ~[atj.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:267) [lr.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:202) [ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[01:17:08] [Server thread/INFO] [STDERR]: [net.minecraft.server.MinecraftServer:func_71267_a:638]: net.minecraft.world.MinecraftException: The save folder for world .\world\DIM-1 is being accessed from another location, aborting
[01:17:08] [Server thread/INFO] [STDERR]: [net.minecraft.server.MinecraftServer:func_71267_a:638]:  at net.minecraft.world.storage.SaveHandler.func_75762_c(SaveHandler.java:96)
[01:17:09] [Server thread/INFO] [STDERR]: [net.minecraft.server.MinecraftServer:func_71267_a:638]:  at net.minecraft.world.World.func_72906_B(World.java:3430)
[01:17:09] [Server thread/INFO] [STDERR]: [net.minecraft.server.MinecraftServer:func_71267_a:638]:  at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:1037)
[01:17:09] [Server thread/INFO] [STDERR]: [net.minecraft.server.MinecraftServer:func_71267_a:638]:  at net.minecraft.world.WorldServerMulti.func_73042_a(WorldServerMulti.java:96)
[01:17:09] [Server thread/INFO] [STDERR]: [net.minecraft.server.MinecraftServer:func_71267_a:638]:  at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1005)
[01:17:09] [Server thread/INFO] [STDERR]: [net.minecraft.server.MinecraftServer:func_71267_a:638]:  at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:512)
[01:17:09] [Server thread/INFO] [STDERR]: [net.minecraft.server.MinecraftServer:func_71267_a:638]:  at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:636)
[01:17:09] [Server thread/INFO] [STDERR]: [net.minecraft.server.MinecraftServer:func_71267_a:638]:  at net.minecraft.server.MinecraftServer.constant$getSaveTickInterval$0(MinecraftServer.java:591)
[01:17:09] [Server thread/INFO] [STDERR]: [net.minecraft.server.MinecraftServer:func_71267_a:638]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:632)
[01:17:09] [Server thread/INFO] [STDERR]: [net.minecraft.server.MinecraftServer:func_71267_a:638]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[01:17:09] [Server thread/INFO] [STDERR]: [net.minecraft.server.MinecraftServer:func_71267_a:638]:  at java.lang.Thread.run(Unknown Source)`

**Comment by ThornsOfire** [comment]
I have posted this error to Sponge Forge, they are helping me test. @trentech I'll let you know what comes of it.

**Comment by trentech** [comment]
Is there a referenced issue ticket?

**Comment by ThornsOfire** [comment]
No reference tick was issues. Other world management plugins don't cause the same issue. Did some more testing though, seems like it only happens when a player does a save-all in game. Console save-all doesn't throw the error.

**Comment by trentech** [comment]
I have no answers. The only change between this and 1.8.9 version is...well that it's built for 1.10.2. I changed almost nothing. I still believe this to be a Sponge error. Worlds all show up as loaded and unloaded at the same time which is the most likely the cause of this error but that's handled by Sponge. The only listeners I have just set gamerules on load and nothing is being cached. There are no asynchronous tasks and 90% of this plugin is just commands and they wouldn't be causing this so...I've got nothing. This program only started occurring after the World Management API was updated. If someone identifies it to in fact be a bug I will gladly fix it but until then I've pretty much given up.

**Comment by trentech** [comment]
So running tests with latest dev builds, this actually isn't happening anymore. Not sure what changed..

**Comment by 5tingr4y** [comment]
Updated to Spongeforge 1752 (latest beta build) and It's still happening for me.

**Comment by trentech** [comment]
When I said latest test builds I was referring to unreleased stuff

**Comment by 5tingr4y** [comment]
Oh ok, sorry ^^

**Comment by trentech** [comment]
Test it out and see if the problem is resolved..Mind you this is a test build so other unrelated problems way be present.

https://www.dropbox.com/s/7f9qkwu2v76tvu3/projectworlds-5.0.0-0.10.4.jar?dl=0

**Comment by 5tingr4y** [comment]
Yup, didn't get the error with that version anymore.
List is correct and the saving problem is also gone.

**Comment by trentech** [comment]
Interesting. I have no idea what I changed that fixed the issue. I've been doing a lot of backend work on all my plugins for API 5.x, nothing related to any specific issues. I'm not sure when I'm going to be pushing these changes. API 5.x is supposedly coming out of bleeding soon so I've been stalling a little bit.

**Comment by trentech** [comment]
Development build has been updated. I've been testing this all night and have had no issues so I'm going to consider this resolved.
