### ISSUE TITLE
/world fill - ClassCastException - Branch 6.0.0

### ISSUE THREAD

**Issue by BrainStone** [trentech/ProjectWorlds#57]
When executing the `/world fill` command and specifing an tick interval the following exception occurs:

```
[23:44:34] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'world fill  world 10000 0' for source DedicatedServer: java.lang.String cannot be cast to java.lang.Integer
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at com.gmail.trentech.pjw.commands.CMDFill.execute(CMDFill.java:84) ~[CMDFill.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:182) ~[ChildCommandElementExecutor.class:1.11.2-6.0.0-BETA-243]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.11.2-6.0.0-BETA-243]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.11.2-6.0.0-BETA-243]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:296) [SpongeCommandManager.class:1.11.2-6.0.0-BETA-243]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [bd.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(SourceFile:368) [lh.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:336) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:562) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:466) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```

**Comment by trentech** [comment]
Resolved in latest dev build

http://trentech.org/jenkins/job/Project%20Worlds/
