### ISSUE TITLE
Cant generate world

### ISSUE THREAD

**Issue by tjkenmate** [trentech/ProjectWorlds#59]
java.lang.IllegalArgumentException: Invalid dimension id 2
	at net.minecraft.world.DimensionType.lambda$getById$0(SourceFile:636)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at net.minecraft.world.DimensionType.func_186069_a(SourceFile:636)
	at net.minecraft.world.WorldServer.<init>(SourceFile:121)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:799)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:770)
	at net.minecraft.server.MinecraftServer.func_71247_a(SourceFile:3726)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:229)
	at net.minecraft.server.MinecraftServer.run(SourceFile:436)
	at java.lang.Thread.run(Thread.java:745)

**Comment by trentech** [comment]
> java.lang.IllegalArgumentException: Invalid dimension id 2

You're world has an invalid dimension id.

**Comment by tjkenmate** [comment]
i just have to ask, how do I assign a dimention ID. the server is spongevanilla

**Comment by trentech** [comment]
This is supposed to be handled internally by Sponge implementation. It's possible that it id is conflicting with another world. This can happen when importing worlds. I would recommend using an NBT editor such as NBT explorer to inspect the level.dat file's and make sure each world has a unique dimension id.
