### ISSUE TITLE
Rnaming default worlds doesnt replace when server restart

### ISSUE THREAD

**Issue by joshuasm** [trentech/ProjectWorlds#66]
I tried renaming DIM-1 to nether, and it all works but when I restart the server it regenerates DIM-1.
Is there another way of renaming the default worlds, or is it not possible?

**Comment by trentech** [comment]
You'd have to disable nether in server.properties after renaming it

**Comment by joshuasm** [comment]
would a nether portal then still direct too that same dimension?

**Comment by trentech** [comment]
Didn't think about that..I'm not sure. There's something in the sponge config regarding setting nether portal destination that might make for a usable work around

**Comment by joshuasm** [comment]
ok so i looked in the sponge configs and changed DIM-1 to nether everywhere where it says 

' portal-agents {
            "minecraft:default_nether"=DIM-1
            "minecraft:default_the_end"=DIM1
        }'

so that's in \configs\sponge i changed the global.conf and all the dimensions in that folder.
it still doesn't work when i disable the nether it disables all the other DIM's and if i try import it says sponge world detected please us /world load and when i load it breaks and gives the stack trace in the screenshot

I tried re-enabling the nether and renaming it from DIM-1 to nether and deleting the DIM-1 after it was recreated and it gave this error in the server:
`[22:20:13] [Server thread/ERROR] [Sponge]: Unable to load world [.\CordlessGamingtest\DIM-1]. We cannot find its folder under [.\CordlessGamingtest].
[22:20:13] [Server thread/ERROR] [Sponge]: Could not load world [DIM-1]!`

it also seems like forge creates the DIM-1 here: 
`[22:16:49] [Server thread/INFO] [FML]: Loading dimension -1 (DIM-1) (DedicatedServer)
[22:16:49] [Server thread/INFO] [Actually Additions]: Successfully received WorldData for world -1!
[22:16:49] [Server thread/INFO] [Sponge]: Loading world [DIM-1] (Nether)`

**Comment by joshuasm** [comment]
also after that closing the server gives this in the server:
`[22:24:44] [Server thread/ERROR]: Exception stopping the server
java.lang.RuntimeException: Attempt made to unload a world with dimension id [1].
        at net.minecraftforge.common.DimensionManager.lambda$setWorld$0(DimensionManager.java:654) ~[DimensionManager.class:?]
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_131]
        at net.minecraftforge.common.DimensionManager.setWorld(DimensionManager.java:654) ~[DimensionManager.class:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:407) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`
