### ISSUE TITLE
Error when trying to create new world

### ISSUE THREAD

**Issue by MTMasterGaming** [trentech/ProjectWorlds#77]
Hi there, I get an error "null" when trying to create a void world using the sponge:void modifier. Can you tell me what I am doing wrong? 

`[16:13:17 INFO] [nucleus]: Charixx ran the command: /world create BWMap -d minecraft:overworld -m sponge:void
[16:13:17 ERROR] [Sponge]: Error occurred while executing command 'world create BWMap -d minecraft:overworld -m sponge:void' for source EntityPlayerMP['Charixx'/416, l='world', x=-242.70, y=92.23, z=-95.70]: null
java.lang.UnsupportedOperationException: null
        at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_121]
        at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_121]
        at com.gmail.trentech.pjw.commands.CommandCreate.process(CommandCreate.java:119) ~[CommandCreate.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:250) ~[ChildCommandElementExecutor.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:392) ~[CommandSpec.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:322) [SpongeCommandManager.class:1.12.2-7.0.0-BETA-382]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:855) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:842) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-7.0.0-BETA-382]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjl000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-7.0.0-BETA-382]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zib000(SourceFile:4179) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1523) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]`

Also, I tried using the minecraft:default generator type as I wasn't sure if that was the issue, and I still got an error. 
`[16:13:30 INFO] [nucleus]: Charixx ran the command: /world create BWMap -d minecraft:overworld -g minecraft:default -m sponge:void
[16:13:30 ERROR] [Sponge]: Error occurred while executing command 'world create BWMap -d minecraft:overworld -g minecraft:default -m sponge:void' for source EntityPlayerMP['Charixx'/416, l='world', x=-243.12, y=92.23, z=-98.47]: null
java.lang.UnsupportedOperationException: null
        at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_121]
        at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_121]
        at com.gmail.trentech.pjw.commands.CommandCreate.process(CommandCreate.java:119) ~[CommandCreate.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:250) ~[ChildCommandElementExecutor.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:392) ~[CommandSpec.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:322) [SpongeCommandManager.class:1.12.2-7.0.0-BETA-382]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:855) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:842) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-7.0.0-BETA-382]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjl000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-7.0.0-BETA-382]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zib000(SourceFile:4179) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1523) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]`

I also tried just using the sponge:void modifier, and this was the error:
`[16:17:04 ERROR] [Sponge]: Error occurred while executing command 'world create BWMap -m sponge:void' for source EntityPlayerMP['Charixx'/416, l='world', x=-258.51, y=92.23, z=-128.49]: null
java.lang.UnsupportedOperationException: null
        at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_121]
        at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_121]
        at com.gmail.trentech.pjw.commands.CommandCreate.process(CommandCreate.java:119) ~[CommandCreate.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:250) ~[ChildCommandElementExecutor.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:392) ~[CommandSpec.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:322) [SpongeCommandManager.class:1.12.2-7.0.0-BETA-382]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:855) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:842) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-7.0.0-BETA-382]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjl000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-7.0.0-BETA-382]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zib000(SourceFile:4179) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1523) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]`

Not sure if all of these errors are the same or not, I don't have time to read through all of it. However, I have used this plugin a long time ago and not had any issues, I am not sure what changed. When I used it then, I was using the import command instead as I already had a map, but the void world modifier did work just fine. Just so you know, I am using Sponge version 7.0.0, beta 382. Any ideas as to what is wrong?

**Comment by trentech** [comment]
resolved 185aea98a63bb9e4e03e32b6c6998b4202cd2d26
