### ISSUE TITLE
load a world dosn't work

### ISSUE THREAD

**Issue by iOSCem** [trentech/ProjectWorlds#83]
i get thsi error when in do /world load Spawn

`[20:58:34] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task pjw-S-4 owned by Plugin{id=pjw, name=ProjectWorlds, version=0.12.2, description=Multi world management plugin, url=http://github.com/TrenTech/ProjectWorlds, authors=[TrenTech], source=C:\Users\dionn\Downloads\Thom En levi's    Pixelmon Server\mods\projectworlds-7.1.0-0.12.2.jar}, but an error occured.
java.lang.IllegalArgumentException: value already present: 2cd01fe3-3140-43b7-96a9-2e2ffaadb4e2
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[minecraft_server.1.12.2.jar:?]
        at org.spongepowered.common.world.WorldManager.registerWorldProperties(WorldManager.java:325) ~[WorldManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.world.WorldManager.loadWorld(WorldManager.java:604) ~[WorldManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.world.WorldManager.loadWorld(WorldManager.java:561) ~[WorldManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:3619) ~[MinecraftServer.class:?]
        at com.gmail.trentech.pjw.commands.CommandLoad.lambda$process$0(CommandLoad.java:71) ~[CommandLoad.class:?]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-2931]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_161]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:278) [SpongeMod.class:1.12.2-2611-7.1.0-BETA-2931]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_40_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:651) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:589) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]`

**Comment by trentech** [comment]
Looks like you have two worlds with the same uuid. Can you explain how this world was created on the server?
