### ISSUE TITLE
World crash due to exploration of improper dimension specification during bukkit world migration

### ISSUE THREAD

**Issue by ThornsOfire** [trentech/ProjectWorlds#9]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.8.9-1694-3.1.0-BETA-1084.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 22/01/16 10:23 AM
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.minecraft.world.World.func_175644_a(World.java:2970)
	at net.minecraft.entity.ai.EntityAINearestAttackableTarget.onGetEntitiesWithinAABB(SourceFile:89)
	at net.minecraft.entity.ai.EntityAINearestAttackableTarget.func_75250_a(SourceFile:72)
	at net.minecraft.entity.monster.EntitySpider$AISpiderTarget.func_75250_a(SourceFile:247)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:72)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:556)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1775)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:382)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:27)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1614)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:228)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:32)
	at net.minecraft.entity.monster.EntitySpider.func_70071_h_(SourceFile:68)
	at net.minecraft.world.World.onCallEntityUpdate(World.java:484)
	at net.minecraft.world.World.func_72866_a(World.java:1860)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699)
	at net.minecraft.world.World.func_72870_g(World.java:1829)
	at net.minecraft.world.World.func_72939_s(World.java:1661)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.minecraft.world.World.func_175644_a(World.java:2970)
	at net.minecraft.entity.ai.EntityAINearestAttackableTarget.onGetEntitiesWithinAABB(SourceFile:89)
	at net.minecraft.entity.ai.EntityAINearestAttackableTarget.func_75250_a(SourceFile:72)
	at net.minecraft.entity.monster.EntitySpider$AISpiderTarget.func_75250_a(SourceFile:247)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:72)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:556)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1775)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:382)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:27)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1614)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:228)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:32)
	at net.minecraft.entity.monster.EntitySpider.func_70071_h_(SourceFile:68)
	at net.minecraft.world.World.onCallEntityUpdate(World.java:484)
	at net.minecraft.world.World.func_72866_a(World.java:1860)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699)
	at net.minecraft.world.World.func_72870_g(World.java:1829)

-- Entity being ticked --
Details:
	Entity Type: Spider (net.minecraft.entity.monster.EntitySpider)
	Entity ID: 1382
	Entity Name: Spider
	Entity's Exact location: -557.50, 4.00, 305.50
	Entity's Block location: -558.00,4.00,305.00 - World: (-558,4,305), Chunk: (at 2,0,1 in -35,19; contains blocks -560,0,304 to -545,255,319), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1661)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)

-- Affected level --
Details:
	Level name: AdminBuilds
	All players: 1 total; [EntityPlayerMP['Peav420'/1517, l='AdminBuilds', x=-559.92, y=25.96, z=354.74]]
	Chunk stats: ServerChunkCache: 898 Drop: 0
	Level seed: 5315498221394719206
	Level generator: ID 09 - overworld, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: -727.00,4.00,432.00 - World: (-727,4,432), Chunk: (at 9,0,0 in -46,27; contains blocks -736,0,432 to -721,255,447), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 324796570 game time, 329532931 day time
	Level dimension: 4
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1052759544 bytes (1003 MB) / 2077753344 bytes (1981 MB) up to 10667687936 bytes (10173 MB)
	JVM Flags: 3 total; -Xms2G -Xmx10G -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.0.1694 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.0.1694-universal.jar) 
	UCHIJAAAA	Forge{11.15.0.1694} [Minecraft Forge] (forge-1.8.9-11.15.0.1694-universal.jar) 
	UCHIJAAAA	sponge{1.8.9-1694-3.1.0-BETA-1084} [SpongeForge] (spongeforge-1.8.9-1694-3.1.0-BETA-1084.jar) 
	UCHIJAAAA	AdminShop{1.3} [AdminShop] (AdminShop-1.3b.jar) 
	UCHIJAAAA	AntiSwear{1.1.3} [AntiSwear] (AntiSwear.jar) 
	UCHIJAAAA	nl.kippers.ArmorHUD{1.0} [ArmorHUD] (ArmorHUD v1.0.jar) 
	UCHIJAAAA	Blood Money{0.2.8} [Blood Money] (BloodMoney.jar) 
	UCHIJAAAA	EssentialCmds{7.0-777f4c9} [EssentialCmds] (EssentialCmds-7.0.jar) 
	UCHIJAAAA	foxcore{0.6.2} [FoxCore] (FoxCore-v0.6.2-70-SNAPSHOT.jar) 
	UCHIJAAAA	Kits{1.3} [Kits] (Kits-1.3.jar) 
	UCHIJAAAA	landiscovery{1.0.1} [LanDiscovery] (landiscovery-1.0.1.jar) 
	UCHIJAAAA	PermissionsEx{2.0-SNAPSHOT} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHIJAAAA	PJP{0.7.26} [Project Portals] (ProjectPortals-3.1.0-v0.7.26.jar) 
	UCHIJAAAA	PJW{0.6.40} [Project Worlds] (ProjectWorlds-3.1.0-v0.6.40.jar) 
	UCHIJAAAA	PvPLogger{1.1} [PvPLogger] (PvPLogger-1.1.jar) 
	UCHIJAAAA	TotalEconomy{1.3.1} [Total Economy] (TotalEconomy-v1.3.1.jar) 
	UCHIJAAAA	Vanish{4.0.0} [Vanish] (vanish.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.8.9-1694-3.1.0-BETA-1084.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['Peav420'/1517, l='AdminBuilds', x=-559.92, y=25.96, z=354.74]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,SpongeForge'
	Type: Dedicated Server (map_server.txt)

**Comment by trentech** [comment]
This crash is an entity issue not world gen related
